# Generated by Django 4.1.2 on 2022-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0002_rename_odkaz_statistika_player_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilization',
            name='emblem',
            field=models.ImageField(upload_to='emblems'),
        ),
    ]
