# Generated by Django 4.1.2 on 2022-10-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0003_alter_civilization_emblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.TextField()),
                ('img', models.ImageField(upload_to='maps')),
            ],
            options={
                'verbose_name': 'Mapa',
                'verbose_name_plural': 'Mapy',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pocet_hracu', models.PositiveSmallIntegerField()),
                ('p1_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p2_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p3_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p4_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p5_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p6_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p7_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p8_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('win', models.PositiveSmallIntegerField()),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.map')),
                ('p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to='ageofpirates.player')),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='ageofpirates.player')),
                ('p3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player3', to='ageofpirates.player')),
                ('p4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player4', to='ageofpirates.player')),
                ('p5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player5', to='ageofpirates.player')),
                ('p6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player6', to='ageofpirates.player')),
                ('p7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player7', to='ageofpirates.player')),
                ('p8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player8', to='ageofpirates.player')),
            ],
            options={
                'verbose_name': 'Hra',
                'verbose_name_plural': 'Hry',
            },
        ),
    ]
