# Generated by Django 4.1.2 on 2022-10-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0004_map_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='datum_cas',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
