# Generated by Django 4.1.2 on 2022-10-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0005_match_datum_cas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
