# Generated by Django 4.1.2 on 2022-10-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0007_match_p1_civ_match_p2_civ_match_p3_civ_match_p4_civ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='popis',
        ),
        migrations.AlterField(
            model_name='civilization',
            name='emblem',
            field=models.ImageField(upload_to='emblems/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='img',
            field=models.ImageField(upload_to='maps/'),
        ),
    ]
