# Generated by Django 4.1.2 on 2022-10-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0010_alter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='delka_hry',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
