# Generated by Django 4.1.2 on 2022-10-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0011_match_delka_hry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hry', models.BigIntegerField(blank=True, null=True)),
                ('vyhry', models.BigIntegerField(blank=True, null=True)),
                ('prohry', models.BigIntegerField(blank=True, null=True)),
                ('rank', models.BigIntegerField(blank=True, null=True)),
                ('hrac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.player')),
            ],
        ),
    ]
