# Generated by Django 4.1.2 on 2022-10-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0012_playerstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.TextField()),
                ('datum_zahajeni', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Turnaj',
                'verbose_name_plural': 'Turnaje',
            },
        ),
    ]
