# Generated by Django 4.1.2 on 2022-10-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0014_tournament_pocet_hracu_tournament_vitez'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='info_ef',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='info_f',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='info_qf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='info_sf',
            field=models.TextField(blank=True),
        ),
    ]
