# Generated by Django 4.1.2 on 2022-10-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0015_tournament_info_tournament_info_ef_tournament_info_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='p1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer1', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer10', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer11', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer12', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer13', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer14', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer15', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer16', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer2', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer3', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer4', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer5', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer6', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer7', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer8', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='p9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tplayer9', to='ageofpirates.player'),
        ),
    ]
