# Generated by Django 4.1.2 on 2022-10-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0016_tournament_p1_tournament_p10_tournament_p11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='qfa1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qplayer1', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qfa2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qplayer2', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qfb1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qplayer3', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qfb2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qplayer4', to='ageofpirates.player'),
        ),
    ]
