# Generated by Django 4.1.2 on 2022-10-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0017_tournament_qfa1_tournament_qfa2_tournament_qfb1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='f1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fplayer1', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='f2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fplayer2', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qfc1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qplayer5', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qfc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qplayer6', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qfd1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qplayer7', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qfd2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qplayer8', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sfa1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splayer1', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sfa2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splayer2', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sfb1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splayer3', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sfb2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splayer4', to='ageofpirates.player'),
        ),
    ]
