# Generated by Django 4.1.2 on 2022-10-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0019_tournament_f1_score_tournament_f2_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fb1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bplayer1', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fb1_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fb2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bplayer2', to='ageofpirates.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fb2_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
