# Generated by Django 4.1.2 on 2022-10-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0020_tournament_fb1_tournament_fb1_score_tournament_fb2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='map1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map1', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map10', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map2', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map3', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map4', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map5', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map6', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map7', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map8', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map9', to='ageofpirates.map'),
        ),
    ]
