# Generated by Django 4.1.2 on 2022-10-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0021_tournament_map1_tournament_map10_tournament_map2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='map11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map11', to='ageofpirates.map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map12', to='ageofpirates.map'),
        ),
    ]
