# Generated by Django 4.1.2 on 2022-10-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0022_tournament_map11_tournament_map12'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='odehrane_hry',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='prohry',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='vyhry',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='wl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
