# Generated by Django 4.1.2 on 2022-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0023_player_odehrane_hry_player_prohry_player_vyhry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='wl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
