# Generated by Django 4.1.2 on 2022-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0024_alter_player_wl'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilization',
            name='hry',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilization',
            name='vyhry',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
