# Generated by Django 4.1.2 on 2022-10-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0025_civilization_hry_civilization_vyhry'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilization',
            name='hry_proc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='civilization',
            name='vyhry_proc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
