# Generated by Django 4.1.2 on 2022-10-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0026_civilization_hry_proc_civilization_vyhry_proc'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='hry',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='hry_proc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='prum_doba',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
