# Generated by Django 4.1.2 on 2022-10-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0027_map_hry_map_hry_proc_map_prum_doba'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef1', models.BooleanField(default=False)),
                ('ef2', models.BooleanField(default=False)),
                ('ef3', models.BooleanField(default=False)),
                ('ef4', models.BooleanField(default=False)),
                ('ef5', models.BooleanField(default=False)),
                ('ef6', models.BooleanField(default=False)),
                ('ef7', models.BooleanField(default=False)),
                ('ef8', models.BooleanField(default=False)),
                ('qf1', models.BooleanField(default=False)),
                ('qf2', models.BooleanField(default=False)),
                ('qf3', models.BooleanField(default=False)),
                ('qf4', models.BooleanField(default=False)),
                ('qf', models.BooleanField(default=False)),
                ('qfb', models.BooleanField(default=False)),
                ('hra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.match')),
            ],
        ),
    ]
