# Generated by Django 4.1.2 on 2022-10-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0028_tournamentmatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentmatch',
            options={'verbose_name': 'Turnajová hra', 'verbose_name_plural': 'Turnajové hry'},
        ),
    ]
