# Generated by Django 4.1.2 on 2022-10-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0029_alter_tournamentmatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='turnaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.tournament'),
        ),
    ]
