# Generated by Django 4.1.2 on 2022-10-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0030_tournamentmatch_turnaj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentmatch',
            old_name='qf',
            new_name='f',
        ),
        migrations.RenameField(
            model_name='tournamentmatch',
            old_name='qfb',
            new_name='fb',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='sf1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='sf2',
            field=models.BooleanField(default=False),
        ),
    ]
