# Generated by Django 4.1.2 on 2023-01-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0032_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='elo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MapPlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vyhry', models.BigIntegerField(blank=True, null=True)),
                ('prohry', models.BigIntegerField(blank=True, null=True)),
                ('hrac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.player')),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.map')),
            ],
        ),
        migrations.CreateModel(
            name='MapCivStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vyhry', models.BigIntegerField(blank=True, null=True)),
                ('prohry', models.BigIntegerField(blank=True, null=True)),
                ('civ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.civilization')),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.map')),
            ],
        ),
        migrations.CreateModel(
            name='CivPlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vyhry', models.BigIntegerField(blank=True, null=True)),
                ('prohry', models.BigIntegerField(blank=True, null=True)),
                ('civ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.civilization')),
                ('hrac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ageofpirates.player')),
            ],
        ),
    ]
