# Generated by Django 4.1.2 on 2023-01-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0033_playerstat_elo_mapplayerstat_mapcivstat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='wl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
