# Generated by Django 4.1.2 on 2023-01-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0034_alter_player_wl'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilization',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
