# Generated by Django 4.1.2 on 2023-01-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0035_civilization_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='delka_hry',
        ),
    ]
