# Generated by Django 4.1.2 on 2023-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageofpirates', '0036_remove_match_delka_hry'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
